-- lab5

-- possible responses
-- insert into Possibilities (qtype, QuestionNo, ResponseID, TextPrompt) values();

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 1, "1 - strongly disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 2, "2- disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 3, "3 - somewhat disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 4, "4 - neither agree nor disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 5, "5 - somewhat agree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 6, " 6 - agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 7, "7 - strongly agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 8, "Prefer not to answer");


insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 1, "1 - strongly disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 2, "2- disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 3, "3 - somewhat disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 4, "4 - neither agree nor disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 5, "5 - somewhat agree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 6, " 6 - agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 7, "7 - strongly agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 8, "Prefer not to answer");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 1, "Agriculture");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 2, "Bioinformatics and/or computational biology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 3, "Discipline-based education research (DBER)");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 4, "Engineering");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 5, "Computer science and computer engineering");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 6, "Engineering - Biomedical");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 7, "Engineering (other)");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 8, "Environmental science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 9, "Kinesiology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 10, "anatomy and physiology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 11, "biochemistry");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 12, "general biology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 13, "botany");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 14, "ecology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 15, "evolution");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 16, "genetics");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 17, "zoology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 18, "Marine science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 19, "Mathematics");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 20, "Neuroscience");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 21, "Physical Sciences");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 22, "Astronomy");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 23, "Chemistry");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 24, "Physics");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 25, "Geology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 26, "Soil science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 27, "Statistics and/or Data Science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 28, "Other");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 29, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 1, "1 student");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 2, "2-4 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 3, "5-8 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 4, "9-12 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 5, "more than 12 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 6, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 1, "2");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 2, "3-5");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 3, "6-9");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 4, "10-13");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 5, "More than 13");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 6, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 1, "Faculty member");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 2, "Postdoctoral researcher");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 3, "Graduate student, technician, or staff scientist");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 4, "Other");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 5, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 1, "Laboratory research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 2, "Field research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 3, "Computer-based research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 4, "prefer not to say");


insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 1, "Laboratory research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 2, "Field research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 3, "Computer-based research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 4, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 11, 1, "Enrolled as a full-time student");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 11, 2, "Enrolled as a part-time student ");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 1, "Academic (college or university)");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 2, "Industry - research and development");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 3, "Industry - production and quality control");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 4, "Government ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 5, "Self-employed consulting/fee for service");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 6, "Other");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 7, "Prefer not to answer");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 1, "AA - year");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 2, "Baccalaureate - year");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 3, "Masters of Science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 4, "Ph. D");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 5, "JD");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 6, "MD");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 7, "MBA");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 8, "not applicable ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 9, "Prefer not to answer");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 3, 1, "default - current year, ability to change to any reasonable year");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 1, "At the computer");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 2, "At the lab bench");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 3, "In the field");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 4, "Other");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 1, "At the computer");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 2, "At the lab bench");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 3, "In the field");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 4, "Other");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 1, "At the computer");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 2, "At the lab bench");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 3, "In the field");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 4, "Other");


-- survey
insert into Survey (SurveyId, shortName, name, Description) values(1, "URE Experience", "Undergratuate Research Experience Survey", "This survey asks you to share your undergraduate research experience. As a result of you taking this survey, we will try to recommend a variety of possible jobs and careers.");
insert into Survey (SurveyId, shortName, name, Description) values(2, "Work Experience", "Work Experience Survey", "This survey asks you to share your work experience.");

-- user
insert into User (UserId, name, Email) values(0, "anonymous","");
insert into User (UserId, name, Email) values(1, "Morgan Has","MHas366@icloud.com");
insert into User (UserId, name, Email) values(2, "Oscar Loson","OLoson560@yahoo.com");
insert into User (UserId, name, Email) values(3, "Sydney Leasure","SLeasure615@hotmail.com");
insert into User (UserId, name, Email) values(4, "Octavio Talsma","OTalsma32@yahoo.com");
insert into User (UserId, name, Email) values(5, "Vern Bosley","VBosley84@yahoo.com");
insert into User (UserId, name, Email) values(6, "Monte Wendlandt","MWendlandt412@msn.com");
insert into User (UserId, name, Email) values(7, "Bethanie Tankson","BTankson35@icloud.com");
insert into User (UserId, name, Email) values(8, "Chris Hapeman","CHapeman182@yahoo.com");
insert into User (UserId, name, Email) values(9, "Andrew Mesia","AMesia23@hotmail.com");
insert into User (UserId, name, Email) values(10, "Reginald Spiva","RSpiva579@icloud.com");
insert into User (UserId, name, Email) values(11, "Lajuana Battenhouse","LBattenhouse794@icloud.com");
insert into User (UserId, name, Email) values(12, "Lin Isreal","LIsreal918@icloud.com");
insert into User (UserId, name, Email) values(13, "Wilber Gavette","WGavette477@yahoo.com");
insert into User (UserId, name, Email) values(14, "Andreas Wiechert","AWiechert153@icloud.com");
insert into User (UserId, name, Email) values(15, "Michel Seabrook","MSeabrook945@icloud.com");
insert into User (UserId, name, Email) values(16, "Tamisha Melgar","TMelgar570@msn.com");
insert into User (UserId, name, Email) values(17, "Maurice Dalbeck","MDalbeck773@yahoo.com");
insert into User (UserId, name, Email) values(18, "Suanne Phaymany","SPhaymany50@yahoo.com");
insert into User (UserId, name, Email) values(19, "Dean Zimbelman","DZimbelman148@hotmail.com");
insert into User (UserId, name, Email) values(20, "Salome Lawhead","SLawhead118@gmail.com");
insert into User (UserId, name, Email) values(21, "Arvilla Mcclurg","AMcclurg955@hotmail.com");
insert into User (UserId, name, Email) values(22, "Shery Snyder","SSnyder946@yahoo.com");
insert into User (UserId, name, Email) values(23, "Jong Underkofler","JUnderkofler587@hotmail.com");
insert into User (UserId, name, Email) values(24, "Michel Aderhold","MAderhold29@yahoo.com");
insert into User (UserId, name, Email) values(25, "Armando Eichman","AEichman151@msn.com");

-- profile char

-- insert into ProfileChars (Id, dimension, characteristics, descrp) values(, "", "", "");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(1, "Task Characteristics", "Work Scheduling Autonomy", "Work scheduling autonomy means that you are able to determine when, and the order in which, you complete your work tasks without having to check in with a supervisor or coworkers. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(2, "Task Characteristics", "Decision Making Autonomy", "Decision making autonomy means that you are able to make decisions about various aspects of your work without having to check in with a supervisor or coworkers. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(3, "Task Characteristics", "Work Methods Autonomy", "Work methods autonomy means that you are able to choose the approach and methods you use for your work without having to check in with a supervisor or coworker.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(4, "Task Characteristics", "Task Variety", "Task variety means that the work you do involves a lot of different kinds tasks and activities, with relatively little time spent doing the same things over and over.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(5, "Task Characteristics", "Task Significance", "Task significance means that the work that you do has – or can have – an important direct or indirect impact on the lives of other people. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(6, "Task Characteristics", "Task Identity", "Task identity means that your work has an identifiable stating point, and ending point, so you know when you’ve ‘finished’ something. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(7, "Task Characteristics", "Feedback from Job", "Feedback from the job means that your work provides you with clear information relating to the quality and quantity of your job performance.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(8, "Knowledge Characteristics", "Job Complexity", "Job complexity means that your job requires you to work on multiple, often complicated, tasks simultaneously.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(9, "Knowledge Characteristics", "Information Processing", "Information processing means that your job requires you to keep track of and analyze a large amount of information in order to complete your work. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(10, "Knowledge Characteristics", "Problem Solving", "Problem solving means that your job requires you be creative in finding solutions to problems with no conspicuous or obvious answer. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(11, "Knowledge Characteristics", "Skill Variety", "Skill variety means that your job requires you to use a range of different or high-level skills to complete your work tasks. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(12, "Knowledge Characteristics", "Specialization", "Specialization means that your job requires you to have well-developed knowledge, and a focused set of skills, in order to complete your work.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(13, "Social characteristics", "Social Support", "Social support means that your job provides you with the opportunity to develop meaningful personal connections with your coworkers.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(14, "Social characteristics", "Initiated Interdependence ", "Initiated interdependence means that for others to complete their work, including coworkers, depends on you getting your work done first.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(15, "Social characteristics", "Received Interdependence", "Received interdependence means that in order for you to complete your work that others, including coworkers, must complete their work first. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(16, "Social characteristics", "Interaction Outside Research Group", " Interaction outside the research group means that your job requires you to have frequent interactions and communication with people outside of your team or group in order to complete your work.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(17, "Social characteristics", "Feedback from Others", " Feedback from others means that, while on the job, coworkers and supervisors provide you with useful information about your work performance.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(18, "Social characteristics", "*Faculty/project leader feedback", "Faculty/project leader feedback means that, while on the job, your faculty/project leader provides you with useful information about your work performance. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(19, "Social characteristics", "*Peer Feedback", " Peer feedback means that, while on the job, your peers provide you with useful information about your work performance.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(20, "Work Context", "Ergonomics", "Ergonomics means that the physical configuration of your work space is generally comfortable, can accommodate a range of different body types, and doesn’t contribute to physical strain or discomfort.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(21, "Work Context", "Physical Demands", "Physical demands means that, while on the job, a great deal of physical effort is necessary to complete your work tasks.   ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(22, "Work Context", "Work Conditions", "Work conditions means that the physical setting where you do your job tasks is generally free from uncomfortable or dangerous conditions.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(23, "Work Context", "Equipment Use", " Equipment use means that, while on the job, your work requires you to use a number of different kinds of equipment to complete your work tasks. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(24, "Work Context", "**Setting", "Work setting can vary in regards to how time is spent between the laboratory (working with reagents and equipment), computers (working with files), fieldwork (collecting samples or making observations in the natural environment) and working with people (teaching, sales, management work).");

--questions
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 1.0, "What is the primary discipline of your research?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 2.0, "How many undergraduate students, including yourself, are/were in your research group at the time of your participation?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 3.0, "How many people in total were in your research group?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 4.0, "Who was primarily responsible for mentoring and expert advice related to your research?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 5.0, "What was the primary setting for your research?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 6.0, "Approximately how was your research time distributed between settings?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 7.0, "How many hours per week did you work on research-related activities in your most recent research experience?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 8.0, "During the same time period, how many hours per week did you devote to extracurricular activities (such as clubs, volunteering, sports, music or theater, other hobbies)?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 9.0, "During the same time period, how many hours per week did you work in a paid job unrelated to your research (on campus or off campus).", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 10.0, "During the same time period, how many hours per week did you devote to other commitments or obligations that were not listed above? (e.g. caring for family members, unpaid work in a family business).", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 11.0, " During the same time period, what was your status in terms of academic courses or units?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 12.0, "The research position allows me to make my own decisions about how to schedule my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 13.0, "The research position allows me to decide on the order in which things are done.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 14.0, "The research position allows me to plan how I do my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 15.0, "The research position gives me a chance to use my personal initiative or judgment in carrying out the work.", 1.0, "decision making autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 16.0, "The research position allows me to make a lot of decisions on my own.", 1.0, "decision making autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 17.0, "The research position provides me with significant autonomy in making decisions.", 1.0, "decision making autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 18.0, "The research position allows me to make decisions about what methods I use to complete my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 19.0, "The research position gives me considerable opportunity for independence and freedom in how I do the work.", 1.0, "work methods autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 20.0, "The research position allows me to decide on my own how to go about doing my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 21.0, "The research position involves a great deal of task variety.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 22.0, "The research position involves doing a number of different things.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 23.0, "The research position requires the performance of a wide range of tasks.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 24.0, "The research position involves performing a variety of tasks.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 25.0, "The results of my work are likely to significantly affect the lives of other people.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 26.0, "The research position itself is very significant and important in the broader scheme of things.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 27.0, "The research position has a large impact on people outside the organization.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 28.0, "The work performed in the research position has a significant impact on people outside my research group.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 29.0, "The research position involves completing a piece of work that has an obvious beginning and end.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 30.0, "The research position is arranged so that I can do an entire piece of work from beginning to end.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 31.0, "The research position provides me the chance to completely finish the pieces of work I begin.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 32.0, "The research position allows me to complete work I start.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 33.0, "The work activities themselves provide direct and clear information about the effectiveness (e.g., quality and quantity) of my performance.", 1.0, "feedback from job");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 34.0, "The research position itself provides feedback on my performance.", 1.0, "feedback from job");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 35.0, "The research position itself provides me with information about my performance.", 1.0, "feedback from job");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 36.0, "The research position requires that I only do one task or activity at a time.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 37.0, "The tasks of the research position are simple and uncomplicated.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 38.0, "The research position comprises relatively uncomplicated tasks.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 39.0, "The research position involves performing relatively simple tasks.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 40.0, "The research position requires me to monitor a great deal of information.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 41.0, "The research position requires that I engage in a large amount of thinking.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 42.0, "The research position requires me to keep track of more than one thing at a time.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 43.0, "The research position requires me to analyze a lot of information.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 44.0, "The research position involves solving problems that have no obvious correct answer.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 45.0, "The research position requires me to be creative.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 46.0, "The research position often involves dealing with problems that I have not met before.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 47.0, "The research position requires unique ideas or solutions to problems.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 48.0, "The research position requires a variety of skills.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 49.0, "The research position requires me to utilize a variety of different skills in order to complete the work.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 50.0, "The research position requires me to use a number of complex or high-level skills.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 51.0, "The research position requires the use of a number of skills.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 52.0, "The research position is highly specialized in terms of purpose, tasks, or activities.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 53.0, "The tools, procedures, materials, and so forth used in this research position are highly specialized in terms of purpose.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 54.0, "The research position requires very specialized knowledge and skills.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 55.0, "The research position requires a depth of knowledge and expertise.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 56.0, "I have the opportunity to develop close friendships in this research position.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 57.0, "I have the chance in this research position to get to know other people.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 58.0, "I have the opportunity to meet with others in this research position.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 59.0, "My group leader is concerned about the welfare of the people in the research group.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 60.0, "People I work with take a personal interest in me.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 61.0, "People I work with are friendly.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 62.0, "The research position requires me to accomplish my work before others complete their work.", 1.0, "initiated interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 63.0, "Other jobs depend directly on my job.", 1.0, "initiated interdepenence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 64.0, "Unless my job gets done, other jobs cannot be completed.", 1.0, "initiated interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 65.0, "My research activities are greatly affected by the work of other people.", 1.0, "received interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 66.0, "The research project depends on the work of many different people for its completion.", 1.0, "received interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 67.0, "My work cannot be done unless others do their work.", 1.0, "received interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 68.0, "The research position requires spending a great deal of time with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 69.0, "The research position involves interaction with people who are not members of my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 70.0, "In this research position, I frequently communicate with people who do not work in the same research group as I do.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 71.0, "The research position involves a great deal of interaction with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 72.0, "I receive a great deal of information from my project leader and peers about my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 73.0, "Other people in the research group, such as group leader and peers, provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 74.0, "I receive feedback on my performance from other people in my group (such as my project leader or peers).", 1.0, "feedback from others");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 75.0, "I receive a great deal of information from my group leader about my work performance.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 76.0, "My group leader provides information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "faculty/projecdt leader feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 77.0, "I receive feedback on my performance from my group leader.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 78.0, "I receive a great deal of information from other students in my group about my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 79.0, "Other students in the research group provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 80.0, "I receive feedback on my performance from other students in my group.", 1.0, "peer feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 81.0, "The seating arrangements in my research space are adequate (e.g., ample opportunities to sit, comfortable chairs, good postural support).", 1.0, "ergonomics");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 82.0, "The research space allows for all size differences between people in terms of clearance, reach, eye height, legroom, etc.", 1.0, "ergonomics");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 83.0, "The research position involves excessive reaching.", 1.0, "ergonomics");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 84.0, "The research position requires a great deal of muscular endurance.", 1.0, "physical demands");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 85.0, "The research position requires a great deal of muscular strength.", 1.0, "physical demands");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 86.0, "The research position requires a lot of physical effort.", 1.0, "physical demands");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 87.0, "The research space is free from excessive noise.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 88.0, "The climate in the research space is comfortable in terms of temperature and humidity.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 89.0, "The research position has a low risk of accident.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 90.0, "The research position takes place in an environment free from health hazards (e.g., chemicals, fumes, etc.).", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 91.0, "The research position occurs in a clean environment.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 92.0, "The research position involves the use of a variety of different equipment.", 1.0, "equipment use");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 93.0, "The research position involves the use of complex equipment or technology.", 1.0, "equipment use");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (1.0, 94.0, "A lot of time was required to learn the equipment used in the research position.", 1.0, "equipment use");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 1.0, "What type of organization do you work in?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 2.0, "Which of degrees did you earn and what year did you earn them in (fill all that apply)", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 3.0, "In which year did you work at the position for which you are answering the survey?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 4.0, "How do you spend your time in this job (fieldwork)?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (nan, 5.0, "How do you spend your time in this job (lab work)?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (nan, 6.0, "How do you spend your time in this job (computer work)?", 0.0, "nan");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 7.0, "The job allows me to make my own decisions about how to schedule my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 8.0, "The job allows me to decide on the order in which things are done.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 9.0, "The job allows me to plan how I do my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 10.0, "The job gives me a chance to use my personal initiative or judgment in carrying out the work.", 1.0, "decision making autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 11.0, "The job allows me to make a lot of decisions on my own.", 1.0, "decision making autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 12.0, "The job provides me with significant autonomy in making decisions.", 1.0, "decision making autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 13.0, "The job allows me to make decisions about what methods I use to complete my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 14.0, "The job gives me considerable opportunity for independence and freedom in how I do the work.", 1.0, "work methods autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 15.0, "The job allows me to decide on my own how to go about doing my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 16.0, "The job involves a great deal of task variety.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 17.0, "The job involves doing a number of different things.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 18.0, "The job requires the performance of a wide range of tasks.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 19.0, "The job involves performing a variety of tasks.", 1.0, "task variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 20.0, "The results of my work are likely to significantly affect the lives of other people.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 21.0, "The job itself is very significant and important in the broader scheme of things.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 22.0, "The job has a large impact on people outside the organization.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 23.0, "The work performed in the job has a significant impact on people outside my research group.", 1.0, "task significance");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 24.0, "The job involves completing a piece of work that has an obvious beginning and end.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 25.0, "The job is arranged so that I can do an entire piece of work from beginning to end.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 26.0, "The job provides me the chance to completely finish the pieces of work I begin.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 27.0, "The job allows me to complete work I start.", 1.0, "task identity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 28.0, "The work activities themselves provide direct and clear information about the effectiveness (e.g., quality and quantity) of my performance.", 1.0, "feedback from job");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 29.0, "The job itself provides feedback on my performance.", 1.0, "feedback from job");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 30.0, "The job itself provides me with information about my performance.", 1.0, "feedback from job");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 31.0, "The job requires that I only do one task or activity at a time.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 32.0, "The tasks of the job are simple and uncomplicated.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 33.0, "The job comprises relatively uncomplicated tasks.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 34.0, "The job involves performing relatively simple tasks.", 1.0, "job complexity");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 35.0, "The job requires me to monitor a great deal of information.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 36.0, "The job requires that I engage in a large amount of thinking.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 37.0, "The job requires me to keep track of more than one thing at a time.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 38.0, "The job requires me to analyze a lot of information.", 1.0, "information processing");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 39.0, "The job involves solving problems that have no obvious correct answer.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 40.0, "The job requires me to be creative.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 41.0, "The job often involves dealing with problems that I have not met before.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 42.0, "The job requires unique ideas or solutions to problems.", 1.0, "problem solving");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 43.0, "The job requires a variety of skills.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 44.0, "The job requires me to utilize a variety of different skills in order to complete the work.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 45.0, "The job requires me to use a number of complex or high-level skills.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 46.0, "The job requires the use of a number of skills.", 1.0, "skill variety");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 47.0, "The job is highly specialized in terms of purpose, tasks, or activities.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 48.0, "The tools, procedures, materials, and so forth used in this job are highly specialized in terms of purpose.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 49.0, "The job requires very specialized knowledge and skills.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 50.0, "The job requires a depth of knowledge and expertise.", 1.0, "specialization");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 51.0, "I have the opportunity to develop close friendships in this job.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 52.0, "I have the chance in this job to get to know other people.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 53.0, "I have the opportunity to meet with others in this job.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 54.0, "My group leader is concerned about the welfare of the people in the research group.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 55.0, "People I work with take a personal interest in me.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 56.0, "People I work with are friendly.", 1.0, "social support");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 57.0, "The job requires me to accomplish my work before others complete their work.", 1.0, "initiated interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 58.0, "Other jobs depend directly on my job.", 1.0, "initiated interdepenence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 59.0, "Unless my job gets done, other jobs cannot be completed.", 1.0, "initiated interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 60.0, "My research activities are greatly affected by the work of other people.", 1.0, "received interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 61.0, "The research project depends on the work of many different people for its completion.", 1.0, "received interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 62.0, "My work cannot be done unless others do their work.", 1.0, "received interdependence");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 63.0, "The job requires spending a great deal of time with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 64.0, "The job involves interaction with people who are not members of my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 65.0, "In this job, I frequently communicate with people who do not work in the same research group as I do.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 66.0, "The job involves a great deal of interaction with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 67.0, "I receive a great deal of information from my project leader and peers about my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 68.0, "Other people in the research group, such as group leader and peers, provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 69.0, "I receive feedback on my performance from other people in my group (such as my project leader or peers).", 1.0, "feedback from others");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 70.0, "I receive a great deal of information from my group leader about my work performance.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 71.0, "My group leader provides information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "faculty/projecdt leader feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 72.0, "I receive feedback on my performance from my group leader.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 73.0, "I receive a great deal of information from other students in my group about my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 74.0, "Other students in the research group provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 75.0, "I receive feedback on my performance from other students in my group.", 1.0, "peer feedback");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 76.0, "The seating arrangements in my research space are adequate (e.g., ample opportunities to sit, comfortable chairs, good postural support).", 1.0, "ergonomics");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 77.0, "The research space allows for all size differences between people in terms of clearance, reach, eye height, legroom, etc.", 1.0, "ergonomics");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 78.0, "The job involves excessive reaching.", 1.0, "ergonomics");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 79.0, "The job requires a great deal of muscular endurance.", 1.0, "physical demands");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 80.0, "The job requires a great deal of muscular strength.", 1.0, "physical demands");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 81.0, "The job requires a lot of physical effort.", 1.0, "physical demands");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 82.0, "The research space is free from excessive noise.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 83.0, "The climate in the research space is comfortable in terms of temperature and humidity.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 84.0, "The job has a low risk of accident.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 85.0, "The job takes place in an environment free from health hazards (e.g., chemicals, fumes, etc.).", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 86.0, "The job occurs in a clean environment.", 1.0, "work conditions");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 87.0, "The job involves the use of a variety of different equipment.", 1.0, "equipment use");
INSERT INTO Questions (Survey, QuestionId, question, qtype, profChar) VALUES (2.0, 88.0, "The job involves the use of complex equipment or technology.", 1.0, "equipment use");
