
-- insert question responses
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 1, "Agriculture");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 2, "Bioinformatics and/or computational biology");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 3, "Discipline-based education research (DBER)");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 4, "Engineering");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 5, "Computer science and computer engineering");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 6, "Engineering - Biomedical");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 7, "Engineering (other)");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 8, "Environmental science");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 9, "Kinesiology");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 10, "anatomy and physiology");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 11, "biochemistry");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 12, "general biology");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 13, "botany");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 14, "ecology");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 15, "evolution");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 16, "genetics");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 17, "zoology");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 18, "Marine science");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 19, "Mathematics");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 20, "Neuroscience");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 21, "Physical Sciences:");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 22, "Astronomy");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 23, "Chemistry ");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 24, "Physics");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 25, "Geology");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 26, "Soil science");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 27, "Statistics and/or Data Science");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 28, "Other");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 1, 0, "prefer not to say");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 2, 1, "1 student");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 2, 2, "2-4 students");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 2, 3, "5-8 students");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 2, 4, "9-12 students");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 2, 5, "more than 12 students");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 2, 0, "prefer not to say");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 3, 1, "2");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 3, 2, "3-5");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 3, 3, "6-9");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 3, 4, "10-13");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 3, 5, "More than 13");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 3, 0, "prefer not to say");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 4, 1, "Faculty member");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 4, 2, "Postdoctoral researcher");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 4, 3, "Graduate student, technician, or staff scientist");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 4, 4, "Other");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 4, 0, "prefer not to say");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 5, 1, "Laboratory research");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 5, 2, "Field research");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 5, 3, "Computer-based research");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 5, 0, "prefer not to say");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 1, "0 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 2, "1 - 5 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 3, "6 - 10 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 4, "11 - 15 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 5, "16 - 20 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 6, "21 - 25 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 7, "26 - 30 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 8, "more than 30 hours a week");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 6, 0, "Prefer not to say");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 1, "strongly disagree");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 2, "disagree");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 3, "somewhat disagree");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 4, "neither agree nor disagree ");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 5, "somewhat agree ");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 6, "agree");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 7, "strongly agree");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(1, 12, 0, "Prefer not to answer");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 1, 1, "Academic (college or university)");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 1, 2, "Industry - research and development");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 1, 3, "Industry - production and quality control");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 1, 4, "Government");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 1, 5, "Self-employed consulting/fee for service");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 1, 6, "Other");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 1, 0, "Prefer not to answer");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 1, "AA - year");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 2, "Baccalaureate - year");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 3, "Masters of Science");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 4, "Ph. D");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 5, "JD");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 6, "MD");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 7, "MBA");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 8, "not applicable ");
insert into Responses (SurvResp, QuestionNo, Qvalue, Answer) values(2, 2, 0, "Prefer not to answer");

-- possible responses
-- insert into Possibilities (qtype, QuestionNo, ResponseID, TextPrompt) values();

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 1, "1 - strongly disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 2, "2- disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 3, "3 - somewhat disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 4, "4 - neither agree nor disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 5, "5 - somewhat agree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 6, " 6 - agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 7, "7 - strongly agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 1, 0, 8, "Prefer not to answer");


insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 1, "1 - strongly disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 2, "2- disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 3, "3 - somewhat disagree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 4, "4 - neither agree nor disagree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 5, "5 - somewhat agree ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 6, " 6 - agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 7, "7 - strongly agree");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(1, 2, 0, 8, "Prefer not to answer");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 1, "Agriculture");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 2, "Bioinformatics and/or computational biology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 3, "Discipline-based education research (DBER)");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 4, "Engineering");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 5, "Computer science and computer engineering");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 6, "Engineering - Biomedical");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 7, "Engineering (other)");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 8, "Environmental science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 9, "Kinesiology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 10, "anatomy and physiology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 11, "biochemistry");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 12, "general biology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 13, "botany");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 14, "ecology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 15, "evolution");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 16, "genetics");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 17, "zoology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 18, "Marine science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 19, "Mathematics");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 20, "Neuroscience");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 21, "Physical Sciences");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 22, "Astronomy");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 23, "Chemistry");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 24, "Physics");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 25, "Geology");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 26, "Soil science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 27, "Statistics and/or Data Science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 28, "Other");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 1, 29, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 1, "1 student");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 2, "2-4 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 3, "5-8 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 4, "9-12 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 5, "more than 12 students");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 2, 6, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 1, "2");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 2, "3-5");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 3, "6-9");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 4, "10-13");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 5, "More than 13");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 3, 6, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 1, "Faculty member");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 2, "Postdoctoral researcher");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 3, "Graduate student, technician, or staff scientist");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 4, "Other");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 4, 5, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 1, "Laboratory research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 2, "Field research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 3, "Computer-based research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 5, 4, "prefer not to say");


insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 1, "Laboratory research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 2, "Field research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 3, "Computer-based research");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 6, 4, "prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 7, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 8, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 9, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 1, "0 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 2, "1 - 5 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 3, "6 - 10 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 4, "11 - 15 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 5, "16 - 20 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 6, "21 - 25 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 7, "26 - 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 8, "more than 30 hours a week");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 10, 9, "Prefer not to say");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 11, 1, "Enrolled as a full-time student");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 1, 11, 2, "Enrolled as a part-time student ");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 1, "Academic (college or university)");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 2, "Industry - research and development");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 3, "Industry - production and quality control");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 4, "Government ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 5, "Self-employed consulting/fee for service");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 6, "Other");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 1, 7, "Prefer not to answer");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 1, "AA - year");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 2, "Baccalaureate - year");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 3, "Masters of Science");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 4, "Ph. D");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 5, "JD");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 6, "MD");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 7, "MBA");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 8, "not applicable ");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 2, 9, "Prefer not to answer");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 3, 1, "default - current year, ability to change to any reasonable year");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 1, "At the computer");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 2, "At the lab bench");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 3, "In the field");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 4, 4, "Other");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 1, "At the computer");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 2, "At the lab bench");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 3, "In the field");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 5, 4, "Other");

insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 1, "At the computer");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 2, "At the lab bench");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 3, "In the field");
insert into Possibilities (qtype, survey, QuestionNo, ResponseID, TextPrompt) values(0, 2, 6, 4, "Other");


-- survey
insert into Survey (SurveyId, shortName, name, Description) values(1, "URE Experience", "Undergratuate Research Experience Survey", "This survey asks you to share your undergraduate research experience. As a result of you taking this survey, we will try to recommend a variety of possible jobs and careers.");
insert into Survey (SurveyId, shortName, name, Description) values(2, "Work Experience", "Work Experience Survey", "This survey asks you to share your work experience.");

-- user
insert into User (UserId, name, Email) values(0, "anonymous","");
insert into User (UserId, name, Email) values(1, "Morgan Has","MHas366@icloud.com");
insert into User (UserId, name, Email) values(2, "Oscar Loson","OLoson560@yahoo.com");
insert into User (UserId, name, Email) values(3, "Sydney Leasure","SLeasure615@hotmail.com");
insert into User (UserId, name, Email) values(4, "Octavio Talsma","OTalsma32@yahoo.com");
insert into User (UserId, name, Email) values(5, "Vern Bosley","VBosley84@yahoo.com");
insert into User (UserId, name, Email) values(6, "Monte Wendlandt","MWendlandt412@msn.com");
insert into User (UserId, name, Email) values(7, "Bethanie Tankson","BTankson35@icloud.com");
insert into User (UserId, name, Email) values(8, "Chris Hapeman","CHapeman182@yahoo.com");
insert into User (UserId, name, Email) values(9, "Andrew Mesia","AMesia23@hotmail.com");
insert into User (UserId, name, Email) values(10, "Reginald Spiva","RSpiva579@icloud.com");
insert into User (UserId, name, Email) values(11, "Lajuana Battenhouse","LBattenhouse794@icloud.com");
insert into User (UserId, name, Email) values(12, "Lin Isreal","LIsreal918@icloud.com");
insert into User (UserId, name, Email) values(13, "Wilber Gavette","WGavette477@yahoo.com");
insert into User (UserId, name, Email) values(14, "Andreas Wiechert","AWiechert153@icloud.com");
insert into User (UserId, name, Email) values(15, "Michel Seabrook","MSeabrook945@icloud.com");
insert into User (UserId, name, Email) values(16, "Tamisha Melgar","TMelgar570@msn.com");
insert into User (UserId, name, Email) values(17, "Maurice Dalbeck","MDalbeck773@yahoo.com");
insert into User (UserId, name, Email) values(18, "Suanne Phaymany","SPhaymany50@yahoo.com");
insert into User (UserId, name, Email) values(19, "Dean Zimbelman","DZimbelman148@hotmail.com");
insert into User (UserId, name, Email) values(20, "Salome Lawhead","SLawhead118@gmail.com");
insert into User (UserId, name, Email) values(21, "Arvilla Mcclurg","AMcclurg955@hotmail.com");
insert into User (UserId, name, Email) values(22, "Shery Snyder","SSnyder946@yahoo.com");
insert into User (UserId, name, Email) values(23, "Jong Underkofler","JUnderkofler587@hotmail.com");
insert into User (UserId, name, Email) values(24, "Michel Aderhold","MAderhold29@yahoo.com");
insert into User (UserId, name, Email) values(25, "Armando Eichman","AEichman151@msn.com");

-- profile char

-- insert into ProfileChars (Id, dimension, characteristics, descrp) values(, "", "", "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 1, "What is the primary discipline of your research?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 2, "How many undergraduate students, including yourself, are/were in your research group at the time of your participation?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 3, "How many people in total were in your research group?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 4, "Who was primarily responsible for mentoring and expert advice related to your research?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 5, "What was the primary setting for your research?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 6, "Approximately how was your research time distributed between settings?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 7, "How many hours per week did you work on research-related activities in your most recent research experience?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 8, "During the same time period, how many hours per week did you devote to extracurricular activities (such as clubs, volunteering, sports, music or theater, other hobbies)?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 9, "During the same time period, how many hours per week did you work in a paid job unrelated to your research (on campus or off campus).", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 10, "During the same time period, how many hours per week did you devote to other commitments or obligations that were not listed above? (e.g. caring for family members, unpaid work in a family business).", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 11, " During the same time period, what was your status in terms of academic courses or units?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 12, "The research position allows me to make my own decisions about how to schedule my work.", 1, "work scheduling autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 13, "The research position allows me to decide on the order in which things are done.", 1, "work scheduling autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 14, "The research position allows me to plan how I do my work.", 1, "work scheduling autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 15, "The research position gives me a chance to use my personal initiative or judgment in carrying out the work.", 1, "decision making autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 16, "The research position allows me to make a lot of decisions on my own.", 1, "decision making autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 17, "The research position provides me with significant autonomy in making decisions.", 1, "decision making autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 18, "The research position allows me to make decisions about what methods I use to complete my work.", 1, "work methods autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 19, "The research position gives me considerable opportunity for independence and freedom in how I do the work.", 1, "work methods autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 20, "The research position allows me to decide on my own how to go about doing my work.", 1, "work methods autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 21, "The research position involves a great deal of task variety.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 22, "The research position involves doing a number of different things.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 23, "The research position requires the performance of a wide range of tasks.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 24, "The research position involves performing a variety of tasks.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 25, "The results of my work are likely to significantly affect the lives of other people.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 26, "The research position itself is very significant and important in the broader scheme of things.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 27, "The research position has a large impact on people outside the organization.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 28, "The work performed in the research position has a significant impact on people outside my research group.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 29, "The research position involves completing a piece of work that has an obvious beginning and end.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 30, "The research position is arranged so that I can do an entire piece of work from beginning to end.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 31, "The research position provides me the chance to completely finish the pieces of work I begin.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 32, "The research position allows me to complete work I start.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 33, "The work activities themselves provide direct and clear information about the effectiveness (e.g., quality and quantity) of my performance.", 1, "feedback from job");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 34, "The research position itself provides feedback on my performance.", 1, "feedback from job");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 35, "The research position itself provides me with information about my performance.", 1, "feedback from job");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 36, "The research position requires that I only do one task or activity at a time.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 37, "The tasks of the research position are simple and uncomplicated.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 38, "The research position comprises relatively uncomplicated tasks.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 39, "The research position involves performing relatively simple tasks.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 40, "The research position requires me to monitor a great deal of information.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 41, "The research position requires that I engage in a large amount of thinking.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 42, "The research position requires me to keep track of more than one thing at a time.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 43, "The research position requires me to analyze a lot of information.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 44, "The research position involves solving problems that have no obvious correct answer.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 45, "The research position requires me to be creative.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 46, "The research position often involves dealing with problems that I have not met before.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 47, "The research position requires unique ideas or solutions to problems.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 48, "The research position requires a variety of skills.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 49, "The research position requires me to utilize a variety of different skills in order to complete the work.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 50, "The research position requires me to use a number of complex or high-level skills.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 51, "The research position requires the use of a number of skills.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 52, "The research position is highly specialized in terms of purpose, tasks, or activities.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 53, "The tools, procedures, materials, and so forth used in this research position are highly specialized in terms of purpose.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 54, "The research position requires very specialized knowledge and skills.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 55, "The research position requires a depth of knowledge and expertise.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 56, "I have the opportunity to develop close friendships in this research position.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 57, "I have the chance in this research position to get to know other people.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 58, "I have the opportunity to meet with others in this research position.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 59, "My group leader is concerned about the welfare of the people in the research group.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 60, "People I work with take a personal interest in me.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 61, "People I work with are friendly.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 62, "The research position requires me to accomplish my work before others complete their work.", 1, "initiated interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 63, "Other jobs depend directly on my job.", 1, "initiated interdepenence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 64, "Unless my job gets done, other jobs cannot be completed.", 1, "initiated interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 65, "My research activities are greatly affected by the work of other people.", 1, "received interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 66, "The research project depends on the work of many different people for its completion.", 1, "received interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 67, "My work cannot be done unless others do their work.", 1, "received interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 68, "The research position requires spending a great deal of time with people outside my research group.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 69, "The research position involves interaction with people who are not members of my research group.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 70, "In this research position, I frequently communicate with people who do not work in the same research group as I do.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 71, "The research position involves a great deal of interaction with people outside my research group.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 72, "I receive a great deal of information from my project leader and peers about my work performance.", 1, "feedback from others");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 73, "Other people in the research group, such as group leader and peers, provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1, "feedback from others");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 74, "I receive feedback on my performance from other people in my group (such as my project leader or peers).", 1, "feedback from others");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 75, "I receive a great deal of information from my group leader about my work performance.", 1, "faculty/project leader feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 76, "My group leader provides information about the effectiveness (e.g., quality and quantity) of my work performance.", 1, "faculty/projecdt leader feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 77, "I receive feedback on my performance from my group leader.", 1, "faculty/project leader feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 78, "I receive a great deal of information from other students in my group about my work performance.", 1, "peer feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 79, "Other students in the research group provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1, "peer feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 80, "I receive feedback on my performance from other students in my group.", 1, "peer feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 81, "The seating arrangements in my research space are adequate (e.g., ample opportunities to sit, comfortable chairs, good postural support).", 1, "ergonomics");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 82, "The research space allows for all size differences between people in terms of clearance, reach, eye height, legroom, etc.", 1, "ergonomics");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 83, "The research position involves excessive reaching.", 1, "ergonomics");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 84, "The research position requires a great deal of muscular endurance.", 1, "physical demands");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 85, "The research position requires a great deal of muscular strength.", 1, "physical demands");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 86, "The research position requires a lot of physical effort.", 1, "physical demands");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 87, "The research space is free from excessive noise.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 88, "The climate in the research space is comfortable in terms of temperature and humidity.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 89, "The research position has a low risk of accident.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 90, "The research position takes place in an environment free from health hazards (e.g., chemicals, fumes, etc.).", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 91, "The research position occurs in a clean environment.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 92, "The research position involves the use of a variety of different equipment.", 1, "equipment use");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 93, "The research position involves the use of complex equipment or technology.", 1, "equipment use");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(1, 94, "A lot of time was required to learn the equipment used in the research position.", 1, "equipment use");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 1, "What type of organization do you work in?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 2, "Which of degrees did you earn and what year did you earn them in (fill all that apply)", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 3, "In which year did you work at the position for which you are answering the survey?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 4, "How do you spend your time in this job (fieldwork)?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(, 5, "How do you spend your time in this job (lab work)?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(, 6, "How do you spend your time in this job (computer work)?", 0, "");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 7, "The job allows me to make my own decisions about how to schedule my work.", 1, "work scheduling autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 8, "The job allows me to decide on the order in which things are done.", 1, "work scheduling autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 9, "The job allows me to plan how I do my work.", 1, "work scheduling autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 10, "The job gives me a chance to use my personal initiative or judgment in carrying out the work.", 1, "decision making autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 11, "The job allows me to make a lot of decisions on my own.", 1, "decision making autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 12, "The job provides me with significant autonomy in making decisions.", 1, "decision making autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 13, "The job allows me to make decisions about what methods I use to complete my work.", 1, "work methods autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 14, "The job gives me considerable opportunity for independence and freedom in how I do the work.", 1, "work methods autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 15, "The job allows me to decide on my own how to go about doing my work.", 1, "work methods autonomy");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 16, "The job involves a great deal of task variety.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 17, "The job involves doing a number of different things.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 18, "The job requires the performance of a wide range of tasks.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 19, "The job involves performing a variety of tasks.", 1, "task variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 20, "The results of my work are likely to significantly affect the lives of other people.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 21, "The job itself is very significant and important in the broader scheme of things.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 22, "The job has a large impact on people outside the organization.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 23, "The work performed in the job has a significant impact on people outside my research group.", 1, "task significance");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 24, "The job involves completing a piece of work that has an obvious beginning and end.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 25, "The job is arranged so that I can do an entire piece of work from beginning to end.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 26, "The job provides me the chance to completely finish the pieces of work I begin.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 27, "The job allows me to complete work I start.", 1, "task identity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 28, "The work activities themselves provide direct and clear information about the effectiveness (e.g., quality and quantity) of my performance.", 1, "feedback from job");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 29, "The job itself provides feedback on my performance.", 1, "feedback from job");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 30, "The job itself provides me with information about my performance.", 1, "feedback from job");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 31, "The job requires that I only do one task or activity at a time.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 32, "The tasks of the job are simple and uncomplicated.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 33, "The job comprises relatively uncomplicated tasks.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 34, "The job involves performing relatively simple tasks.", 1, "job complexity");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 35, "The job requires me to monitor a great deal of information.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 36, "The job requires that I engage in a large amount of thinking.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 37, "The job requires me to keep track of more than one thing at a time.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 38, "The job requires me to analyze a lot of information.", 1, "information processing");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 39, "The job involves solving problems that have no obvious correct answer.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 40, "The job requires me to be creative.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 41, "The job often involves dealing with problems that I have not met before.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 42, "The job requires unique ideas or solutions to problems.", 1, "problem solving");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 43, "The job requires a variety of skills.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 44, "The job requires me to utilize a variety of different skills in order to complete the work.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 45, "The job requires me to use a number of complex or high-level skills.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 46, "The job requires the use of a number of skills.", 1, "skill variety");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 47, "The job is highly specialized in terms of purpose, tasks, or activities.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 48, "The tools, procedures, materials, and so forth used in this job are highly specialized in terms of purpose.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 49, "The job requires very specialized knowledge and skills.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 50, "The job requires a depth of knowledge and expertise.", 1, "specialization");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 51, "I have the opportunity to develop close friendships in this job.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 52, "I have the chance in this job to get to know other people.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 53, "I have the opportunity to meet with others in this job.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 54, "My group leader is concerned about the welfare of the people in the research group.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 55, "People I work with take a personal interest in me.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 56, "People I work with are friendly.", 1, "social support");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 57, "The job requires me to accomplish my work before others complete their work.", 1, "initiated interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 58, "Other jobs depend directly on my job.", 1, "initiated interdepenence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 59, "Unless my job gets done, other jobs cannot be completed.", 1, "initiated interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 60, "My research activities are greatly affected by the work of other people.", 1, "received interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 61, "The research project depends on the work of many different people for its completion.", 1, "received interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 62, "My work cannot be done unless others do their work.", 1, "received interdependence");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 63, "The job requires spending a great deal of time with people outside my research group.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 64, "The job involves interaction with people who are not members of my research group.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 65, "In this job, I frequently communicate with people who do not work in the same research group as I do.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 66, "The job involves a great deal of interaction with people outside my research group.", 1, "interaction outside research group");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 67, "I receive a great deal of information from my project leader and peers about my work performance.", 1, "feedback from others");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 68, "Other people in the research group, such as group leader and peers, provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1, "feedback from others");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 69, "I receive feedback on my performance from other people in my group (such as my project leader or peers).", 1, "feedback from others");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 70, "I receive a great deal of information from my group leader about my work performance.", 1, "faculty/project leader feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 71, "My group leader provides information about the effectiveness (e.g., quality and quantity) of my work performance.", 1, "faculty/projecdt leader feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 72, "I receive feedback on my performance from my group leader.", 1, "faculty/project leader feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 73, "I receive a great deal of information from other students in my group about my work performance.", 1, "peer feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 74, "Other students in the research group provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1, "peer feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 75, "I receive feedback on my performance from other students in my group.", 1, "peer feedback");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 76, "The seating arrangements in my research space are adequate (e.g., ample opportunities to sit, comfortable chairs, good postural support).", 1, "ergonomics");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 77, "The research space allows for all size differences between people in terms of clearance, reach, eye height, legroom, etc.", 1, "ergonomics");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 78, "The job involves excessive reaching.", 1, "ergonomics");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 79, "The job requires a great deal of muscular endurance.", 1, "physical demands");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 80, "The job requires a great deal of muscular strength.", 1, "physical demands");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 81, "The job requires a lot of physical effort.", 1, "physical demands");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 82, "The research space is free from excessive noise.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 83, "The climate in the research space is comfortable in terms of temperature and humidity.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 84, "The job has a low risk of accident.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 85, "The job takes place in an environment free from health hazards (e.g., chemicals, fumes, etc.).", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 86, "The job occurs in a clean environment.", 1, "work conditions");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 87, "The job involves the use of a variety of different equipment.", 1, "equipment use");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 88, "The job involves the use of complex equipment or technology.", 1, "equipment use");
insert into Questions (Survey, QuestionId, question, qtype, profChar) values(2, 89, "A lot of time was required to learn the equipment used in the job.", 1, "equipment use");
