
-- profile char

-- insert into ProfileChars (Id, dimension, characteristics, descrp) values(, "", "", "");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(1, "Task Characteristics", "Work Scheduling Autonomy", "Work scheduling autonomy means that you are able to determine when, and the order in which, you complete your work tasks without having to check in with a supervisor or coworkers. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(2, "Task Characteristics", "Decision Making Autonomy", "Decision making autonomy means that you are able to make decisions about various aspects of your work without having to check in with a supervisor or coworkers. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(3, "Task Characteristics", "Work Methods Autonomy", "Work methods autonomy means that you are able to choose the approach and methods you use for your work without having to check in with a supervisor or coworker.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(4, "Task Characteristics", "Task Variety", "Task variety means that the work you do involves a lot of different kinds tasks and activities, with relatively little time spent doing the same things over and over.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(5, "Task Characteristics", "Task Significance", "Task significance means that the work that you do has – or can have – an important direct or indirect impact on the lives of other people. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(6, "Task Characteristics", "Task Identity", "Task identity means that your work has an identifiable stating point, and ending point, so you know when you’ve ‘finished’ something. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(7, "Task Characteristics", "Feedback from Job", "Feedback from the job means that your work provides you with clear information relating to the quality and quantity of your job performance.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(8, "Knowledge Characteristics", "Job Complexity", "Job complexity means that your job requires you to work on multiple, often complicated, tasks simultaneously.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(9, "Knowledge Characteristics", "Information Processing", "Information processing means that your job requires you to keep track of and analyze a large amount of information in order to complete your work. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(10, "Knowledge Characteristics", "Problem Solving", "Problem solving means that your job requires you be creative in finding solutions to problems with no conspicuous or obvious answer. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(11, "Knowledge Characteristics", "Skill Variety", "Skill variety means that your job requires you to use a range of different or high-level skills to complete your work tasks. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(12, "Knowledge Characteristics", "Specialization", "Specialization means that your job requires you to have well-developed knowledge, and a focused set of skills, in order to complete your work.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(13, "Social characteristics", "Social Support", "Social support means that your job provides you with the opportunity to develop meaningful personal connections with your coworkers.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(14, "Social characteristics", "Initiated Interdependence ", "Initiated interdependence means that for others to complete their work, including coworkers, depends on you getting your work done first.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(15, "Social characteristics", "Received Interdependence", "Received interdependence means that in order for you to complete your work that others, including coworkers, must complete their work first. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(16, "Social characteristics", "Interaction Outside Research Group", " Interaction outside the research group means that your job requires you to have frequent interactions and communication with people outside of your team or group in order to complete your work.  ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(17, "Social characteristics", "Feedback from Others", " Feedback from others means that, while on the job, coworkers and supervisors provide you with useful information about your work performance.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(18, "Social characteristics", "*Faculty/project leader feedback", "Faculty/project leader feedback means that, while on the job, your faculty/project leader provides you with useful information about your work performance. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(19, "Social characteristics", "*Peer Feedback", " Peer feedback means that, while on the job, your peers provide you with useful information about your work performance.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(20, "Work Context", "Ergonomics", "Ergonomics means that the physical configuration of your work space is generally comfortable, can accommodate a range of different body types, and doesn’t contribute to physical strain or discomfort.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(21, "Work Context", "Physical Demands", "Physical demands means that, while on the job, a great deal of physical effort is necessary to complete your work tasks.   ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(22, "Work Context", "Work Conditions", "Work conditions means that the physical setting where you do your job tasks is generally free from uncomfortable or dangerous conditions.");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(23, "Work Context", "Equipment Use", " Equipment use means that, while on the job, your work requires you to use a number of different kinds of equipment to complete your work tasks. ");
insert into ProfileChars (Id, dimension, characteristics, descrp) values(24, "Work Context", "**Setting", "Work setting can vary in regards to how time is spent between the laboratory (working with reagents and equipment), computers (working with files), fieldwork (collecting samples or making observations in the natural environment) and working with people (teaching, sales, management work).");

-- desired profiles
insert into DesProfiles (ProfileId, profName, User) values(1, "Dream Job", 1);	
insert into DesProfiles (ProfileId, profName, User) values(2, "Professional Development", 1);	
insert into DesProfiles (ProfileId, profName, User) values(3, "Dream Job", 2);	
insert into DesProfiles (ProfileId, profName, User) values(4, "What I like", 2);	
insert into DesProfiles (ProfileId, profName, User) values(5, "Dream Job", 3);	
insert into DesProfiles (ProfileId, profName, User) values(6, "Best Internship", 5);	
insert into DesProfiles (ProfileId, profName, User) values(7, "Dream Job", 6);	
insert into DesProfiles (ProfileId, profName, User) values(8, "My Internship", 7);	
insert into DesProfiles (ProfileId, profName, User) values(9, "High Tech Career", 8);	
insert into DesProfiles (ProfileId, profName, User) values(10, "High Tech Career", 9);	
insert into DesProfiles (ProfileId, profName, User) values(11, "Lab Tech Job", 9);	
insert into DesProfiles (ProfileId, profName, User) values(12, "Dream Job", 10);	
insert into DesProfiles (ProfileId, profName, User) values(13, "Work-life balance", 10);	
insert into DesProfiles (ProfileId, profName, User) values(14, "My future career", 10);	
insert into DesProfiles (ProfileId, profName, User) values(15, "Dream Job", 14);	
insert into DesProfiles (ProfileId, profName, User) values(16, "Dream Job", 15);	
insert into DesProfiles (ProfileId, profName, User) values(17, "Work-life balance", 15);	
insert into DesProfiles (ProfileId, profName, User) values(18, "Future Career", 17);	
insert into DesProfiles (ProfileId, profName, User) values(19, "Dream Job", 20);	
insert into DesProfiles (ProfileId, profName, User) values(20, "Things I would like to avoid", 21);	
insert into DesProfiles (ProfileId, profName, User) values(21, "Dream Job", 21);	
insert into DesProfiles (ProfileId, profName, User) values(22, "Dream Job", 22);	
insert into DesProfiles (ProfileId, profName, User) values(23, "After graduation", 10);	
insert into DesProfiles (ProfileId, profName, User) values(24, "Bad Jobs", 23);	
insert into DesProfiles (ProfileId, profName, User) values(25, "Dream Job", 25);	
insert into DesProfiles (ProfileId, profName, User) values(26, "After graduation", 4);	
insert into DesProfiles (ProfileId, profName, User) values(27, "Career", 4);	
insert into DesProfiles (ProfileId, profName, User) values(28, "Bad Jobs", 5);	
insert into DesProfiles (ProfileId, profName, User) values(29, "Dream Job", 7);	
insert into DesProfiles (ProfileId, profName, User) values(30, "Career 1", 7);	
insert into DesProfiles (ProfileId, profName, User) values(31, "Career 2", 7);	
insert into DesProfiles (ProfileId, profName, User) values(32, "Work-life balance", 8);	
insert into DesProfiles (ProfileId, profName, User) values(33, "I do not want to work", 10);	
insert into DesProfiles (ProfileId, profName, User) values(34, "Work-life balance", 11);	
insert into DesProfiles (ProfileId, profName, User) values(35, "I do not want to work", 12);	
insert into DesProfiles (ProfileId, profName, User) values(36, "If i did want to work", 12);	
insert into DesProfiles (ProfileId, profName, User) values(37, "Job in sunny California", 13);	
insert into DesProfiles (ProfileId, profName, User) values(38, "My Career plan ", 16);	
insert into DesProfiles (ProfileId, profName, User) values(39, "In search of a good job", 17);	
insert into DesProfiles (ProfileId, profName, User) values(40, "Active job", 18);	
insert into DesProfiles (ProfileId, profName, User) values(41, "Job #4", 19);	
insert into DesProfiles (ProfileId, profName, User) values(42, "Profile #5", 20);	
insert into DesProfiles (ProfileId, profName, User) values(43, "Yawn", 24);	
insert into DesProfiles (ProfileId, profName, User) values(44, "CEO track", 24);	
insert into DesProfiles (ProfileId, profName, User) values(45, "I do not want to work", 25);	
insert into DesProfiles (ProfileId, profName, User) values(46, "Job #2", 12);	
insert into DesProfiles (ProfileId, profName, User) values(47, "My last profile", 12);	
insert into DesProfiles (ProfileId, profName, User) values(48, "Huh", 22);	
insert into DesProfiles (ProfileId, profName, User) values(49, "Huh 2", 22);	
insert into DesProfiles (ProfileId, profName, User) values(50, "Work-life balance", 23);	
